name: Linter
on: [pull_request, push]
jobs:
  lint-checker:
    runs-on: windows-latest
    steps:
      - name: Setup Node.js
      - uses: actions/setup-node@v4
        with:
          node-version: 14.17.0
    
      - name: Install dependencies
        run: npm i
    
      - name: Run linter
        run: npm run lint
